[firebase]
type = "service_account"
project_id = "ligafut-a0056"
private_key_id = "e77a01c2407a9aa411162f506083a3f3f2a761f3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIIxU3KoBVQbio
EM37+KukEXeaRLHQO5d8ypQU6E1tOchzOpv+/AEMkE6WlvagHAL7Oa40rnVW1oi2
lWbFA9cAtpJN2MX//fcrdYaf1vC9lC9FI3PCn9zjV++0m+pNSwux4OjjNty2Rku7
Dr5/UehTirsk7DVY+9iKTd3eU5RrYJ+jr6BzRTHADliJ6zlkwtr+E6A8TyByJghd
ixHvYO0e9k/zec8nMTnNze9xSEKk5384uMA3pJMRst1Hb4iRuBzJTt+D85eOirR2
LSf7TwR6vX4fgJPGGje2qXSeu0A76bkw/S7IOeIeBnPXiY4Y69xbyLZBHmP+qE4C
xOvt9x+rAgMBAAECggEAD7x6cZD88Dcvrr9LgvFlhYv+DHo0RPw6iAxholc1p03w
zeag12a3Kma6Vyrdj29EaL57TRcekMpji3+pyfnoUN0KGebegqdUZO1jvXOoEC/z
m4sTEg2Bz7pdVaUgwh0ReVYG2b65kfdrAvVA0z/8dX0mA9wywaFjwFQpCs8lj1+w
tnhRPHdvY3lM9OUCsmr3AmZ6X98gNqsQzYvBJq8NfhR+VqQUmbm3HdrZI2++y6TA
6wfTl7Nk3oEuviD+jBAQnu1/k1Qs014aOoYf/BGtac2ZJZhBfhBCyVM8ybaCY9fT
tJmE9Sw68c9frS2QhCtWQNGSVXIqNgG6QDOu/lyLSQKBgQD+hw3s2Ai/v8MCQuVC
XZQIBHP5tdBzv9XWUABSyT5uXnoo2reFzQlGwIGxbdUErcso3gOFzE37VnfLeULb
58k9JJK6D2gol50iorsBNrsZ0U9Lmxn5vtPq9nbKyB/Y4F7uRdocBBm7Vhz0iNcu
yutX8htCJuDkFoMGkAX2EPWAtwKBgQDJS3prYfi9K9RIaDYGjnpQ8eYoRYnZK5Fa
HTaN8bZiFH6EPVolS1X19Gj1HntUDbAOoJ698fiesQs3MuN2aR7H2OSPh7vDpEOv
Tf0H6DcKiEsgObZIoxUsh3ZfEpsATd6TQYTdeZi38XpwU42skevtxqMc0HDith8B
s4garH38rQKBgDSxwTBHiYgpKzZMoyoaNYtzYI9SFNXh4WN9LJP3FfXDmYbbwSLy
T/lV4YPaOT++u1C6pgANTBe8zxBRCoZ8di0yZS4gAnBk8yM4jX6y1gmCS+hbNAWA
fF8op29T/0PnL8AktgMW1jzylwwJSINnf1G1ze7kHasa/gVdy94lpK4BAoGBAKAB
TTgaUlwcgMtlerxPeM7q2aZdUCu+Q/W7jufZoL3pyH9ZPVSzw4qUUvG03xd7Id0e
s9AMjTGnTWD9JG21NXBp6ZRlskzbP6oTdfRZE5ddq0ncVhb6+xPAQclkwqzFOQ0Y
YYKi61AbtNWgtNbdzwncgT+gOHsdhRwXFzMMtcCpAoGBAPAN1qF3GYFFrk1DHkey
mE8tWtcs9dp2O6vlPTiaswT9QKgubiPJ85ty/debezhS4K2mW5+k2ma7J/mI42St
NX4kKWqNFaP0pdi8QS9EnJhy0SffZXitMHAw+21Lykdn3WH1IAISfhY9U2bTSHiu
maGtwLS6RubNG+HVjsMq0+OZ
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@ligafut-a0056.iam.gserviceaccount.com"
client_id = "109574403666451846638"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ligafut-a0056.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
