[firebase]
type = "service_account"
project_id = "ligafut-a0056"
private_key_id = "cb6324a0e2f5fa3ed044a05768cad44b8e1b344d"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6SlquYBgrb8kM\nSdtsW5YKY3HxJ8/Xrb6Mh9ZgccDLlzIWP/Be8FTCVEY3FeBstgDSLa+x3L714C/H\n...\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@ligafut-a0056.iam.gserviceaccount.com"
client_id = "109574403666451846638"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ligafut-a0056.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
